### ISSUE TITLE
[help] ways to use "double key" in meow-normal-mode

### ISSUE THREAD

**Issue by qingshuizheng** [nowislewis/nowisemacs#2]
Hi Lewis,
I see these snippets in your .org doc, enabling double keys (not sure about the right term to use, but let's name it that way :-) in meow-normal-mode. I'm wondering how you achieve this. I browse through your meow-related codes, but to no avail.
[init.org#meow](https://github.com/nowislewis/nowisemacs/blob/master/init.org#meow)

```
                                   '("v v" . meow-visit)
.
.
.
                                   '("z a" . hs-toggle-hiding)
                                   '("z c" . hs-hide-block)
                                   '("z o" . hs-show-block)
                                   '("z m" . hs-hide-all)
                                   '("z r" . hs-show-all)
                                   '("v i" . meow-inner-of-thing)
                                   '("v a" . meow-bounds-of-thing)
                                   '("v \'" . insert-quotations)
                                   '("v \"" . insert-quotes)
                                   '("v \`" . insert-backquote)
                                   '("v *" . insert-star)
                                   '("v (" . insert-parentheses)
                                   '("v [" . insert-bracket)
                                   '("v {" . insert-curly)
                                   '("v =" . insert-equation)
```

Really appreciate for any clues.

Zheng

**Comment by nowislewis** [comment]
Hello Zheng, the operation here is a sequence of keys rather than a key combination, that is, when you are in normal mode, pressing “z” will enter a secondary menu, then pressing “a” will toggle the codes under the cursor, pressing “m” will collapse all the code. This button habit is something I absorbed from vim. The reason why it can be written this way is because meow itself only binds the user-supplied keys into a key sequence of the func

**Comment by qingshuizheng** [comment]
Thanks! Apologies for the late reply and appreciate for detailing how it works.

> The reason why it can be written this way is because meow itself only binds the user-supplied keys into a key sequence of the func

Seems that this kind of sequence of keys in meow is not allowed by default? When I set `'("v v" . meow-visit)` in meow-normal-mode, I would receive the error: `meow-define-keys: Key sequence v v starts with non-prefix key v`.

How do you enable it? it's gonna be so cool to have it.

**Comment by nowislewis** [comment]
Can you give a code that reproduces the error? I just tried it out and the code below works well for me:
``` Elisp
(meow-normal-define-key '("z m" . hs-hide-all)
                        '("z r" . hs-show-all)
                        )

```

**Comment by qingshuizheng** [comment]
> Can you give a code that reproduces the error? I just tried it out and the code below works well for me:
> 
> ```emacs-lisp
> (meow-normal-define-key '("z m" . hs-hide-all)
>                         '("z r" . hs-show-all)
>                         )
> ```

Yikes! I tried Meow config with "emacs -Q", and it works. I didn't realize that is there's something messing with meow in my own config, until now. Thanks, I will fix it on my end. Close the issue now. 👍
