### ISSUE TITLE
'make bootstrap-borg & make bootstrap' fail with error 'make: *** [bootstrap] Error 2'

### ISSUE THREAD

**Issue by penn201500** [nowislewis/nowisemacs#3]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/16840448/231340788-67ddb177-d5b8-4298-a440-63b4976028c7.png">

Hello, need some help here, I want to migrate from doom to nowisemacs, but I can not install it. The error info just as the picture shows.

Env:
- emacs 28.2
- Mac Intel-arc, Ventura 13.3.1

Steps:
Just as the readme doc says.

**Comment by nowislewis** [comment]
This is a problem between lsp-bridge with byte-compile, which has nothing to do with nowislewis. And it doesn’t affect a normal use

**Comment by nowislewis** [comment]
You're right. I'll update it tonight: set all these as intelligent judgment and update the instructions. Thank you for your feedback
