### ISSUE TITLE
the gitignore conf maybe not be right

### ISSUE THREAD

**Issue by penn201500** [nowislewis/nowisemacs#4]
Hello, the conf items in .gitignore maybe not be right. For example, there are many new dirs and files added in lib dir after make; it's better to ignore them. Can we move conf files to a dir and other module files or dirs to another place? Just like doomemacs does.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/16840448/231348138-124743ea-0a72-4566-9c1e-8cedd4f01be8.png">

**Comment by penn201500** [comment]
Oh, sorry, got it wrong. Add new packages also related to the .gitignore file.

**Comment by nowislewis** [comment]
Hello, modifications (tracked) to the lib dir are commit of modify's git submodule and they doesn’t matter. I will throw away other redundant untrack parts. Doom's solution is a very good solution. It uses straight, which will be divided into clone directory, compilation directory and running dirs. I used to use straight.el for a long time but for simplicity, nowisemacs uses git submodule, which causes clone and compiled directories to be together. It's easy to debug, but it's a little messy. I need to think about the solution here. Maybe I should write some scripts to seperate these files.

Thanks penn, you offer me a great suggestion

**Comment by penn201500** [comment]
BTW, for those with many self-conf functions or files in doomemacs or spacemacs distribution. They may want to migrate files into nowisemacs. If they can do it quickly, such as "(load! 'xxx')" in doomemac, that'll be better for this project to prompt

**Comment by nowislewis** [comment]
Another way is to add directly in emacs which is more convenient:
1. run M-x borg-assimilate, enter package name and then enter package url
2.  Wait for the package clone to finish and automatic compilation to finish
3.  enter M-x borg-activate to enable the package you just started
now you can directly use commands in the package

**Comment by nowislewis** [comment]
> BTW, for those with many self-conf functions or files in doomemacs or spacemacs distribution. They may want to migrate files into nowisemacs. If they can do it quickly, such as "(load! 'xxx')" in doomemac, that'll be better for this project to prompt

That's a good point of yours. All previous custom functions can be copied directly. Given the compatibility with DOOM, perhaps it would be better to use use-package instead of setup. setup.el is a more native way of writing that encourages direct customization of macros, but it's not generic, and I'm considering removing it outright
