### ISSUE TITLE
there are many warnings at startup

### ISSUE THREAD

**Issue by penn201500** [nowislewis/nowisemacs#5]
There are many warnings at startup, and the issue can be fixed by adding '(setq warning-minimum-level :emergency)' in init.el

Steps:
1. Finish the installation and start the emacs app; I got:
![image](https://user-images.githubusercontent.com/16840448/231417455-b895860d-4ce7-4fd7-b33a-b44df48e3acf.png)

2. Update init.el and execute 'make init-build'
<img width="643" alt="image" src="https://user-images.githubusercontent.com/16840448/231417703-4ddddf8a-772f-49fb-94c9-7458070e659d.png">

3. Start emacs again:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/16840448/231417764-b7ece6ae-4492-4cfb-972d-a72d7a22b767.png">

ref: https://stackoverflow.com/questions/23749267/how-do-i-disable-warnings-at-initialization-in-emacs

**Comment by nowislewis** [comment]
Hi. The problem is that if you enable native-comp, which compiles all third-party packages when emacs is enabled, it will cause performance degradation in daily use. 

A better approach is used in Nowisemacs, where you run “make native” directly, which compiles all third-party packages with native-comp at the command line, and then opens Emacs again and will not compile any more

**Comment by nowislewis** [comment]
I tend to natively compile all packages ahead-of-time, so that it will be very smooth when the user start emacs

**Comment by penn201500** [comment]
Got it, I'll give it a try.

**Comment by penn201500** [comment]
Do you have a TG group or discord server for this project? I want to join in. This is a fantastic project!  
If the IM info is private, could me send me via email [penn201500@gmail.com](mailto:penn201500@gmail.com) ? I'll delete this info later.

**Comment by nowislewis** [comment]
Not yet. This project is a relatively simple configuration. I rely on emacs every day for my work, so any suggestions are welcome.
