### ISSUE TITLE
How to use it in terminal?

### ISSUE THREAD

**Issue by penn201500** [nowislewis/nowisemacs#6]
Can I use it in the terminal? I've just tried 'emacsclient --c -a init.el' and failed. Got:
Waiting for Emacs...
                    *ERROR*: Cannot open load file: No such file or directory, ~/dotfiles/config/.config/emacs/modules/ui/modeline/autoload

**Comment by nowislewis** [comment]
Sorry for replying late, I write some docs about your useful suggestions and play around with new packages such as gptel.
I generally use the terminal's emacs in two ways. 
1. Directly 
``` elisp
emacs -nw 
;; If you want to use a target init.el:
emacs -nw -Q -l ~/.emacs.d/init.el
``` 
3. Use client-server:
``` Elisp
;;first
 emacs --daemon -Q -l ~/.emacs.d/init.el
;; then
emacsclient -r -t
```
